[package]
name = "iter-spool"
description = "The poor man's try_fold"
authors = ["Newton Toto<nyachiengatoto@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT"
keywords = ["no_std", "itertools", "iterator", "spool"]
categories = ["tools", "no_std"]
readme = "README.md"
